# Site settings
title: Jinzhou Ye 叶金州
email: yejz@hust.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  I am analytic philosopher, focusing on the order of public reason, and intelligence, both natural and artificial. Here I share my teaching, research and topics I think useful for students and colleagues.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yejzh.github.io" # the base hostname & protocol for your site
twitter_username: yejzh
github_username:  yejzh
orcid_id: 0000-0002-2740-369X
google_scholar_id: W1PVm1IAAAAJ

comments: true


# Build settings
markdown: kramdown

# Other options
permalink: :year/:month/:title
jobtitle: "Associate Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
